# Generated by Django 5.0 on 2023-12-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0002_ontologyupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ontologyupload",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
