# Generated by Django 5.0 on 2024-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0003_alter_ontologyupload_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ontologyupload",
            name="ontology_type",
            field=models.CharField(default="DATA_CONTEXT", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("DATA_PROVIDER", "Data Subject/Data Provider"),
                    ("DATACONTROLLER_PROCESSOR", "Data Contact/Data Processor"),
                ],
                default="DATA_PROVIDER",
                max_length=100,
            ),
        ),
    ]
