# Generated by Django 5.0 on 2024-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0004_ontologyupload_ontology_type_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("sensor_data", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
