# Generated by Django 5.0 on 2024-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0005_sensordata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("data_subject_data", models.CharField(max_length=255)),
                ("consent_status", models.BooleanField()),
                ("consent_given_date", models.DateField()),
                ("consent_revoked_date", models.DateField()),
                ("consent_given_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
