# Generated by Django 5.0 on 2024-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0006_datasubjectdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasubjectdata",
            name="consent_revoked_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
