# Generated by Django 5.0 on 2024-02-27 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0007_alter_datasubjectdata_consent_revoked_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRequest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("general_ontology", models.CharField(max_length=255)),
                ("domain_ontology", models.CharField(max_length=255)),
                ("schema_ontology", models.CharField(max_length=255)),
                ("consent_data", models.CharField(max_length=255)),
                ("consent_purpose", models.CharField(max_length=255)),
                ("consent_date_start", models.DateField()),
                ("consent_date_end", models.DateField()),
                (
                    "assignee",
                    models.ManyToManyField(
                        related_name="assignee", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "consent_requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_requested_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
