# Generated by Django 5.0 on 2024-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0008_consentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequest",
            name="additional_requests",
            field=models.JSONField(default="{}"),
        ),
        migrations.AddField(
            model_name="consentrequest",
            name="consent_operations",
            field=models.JSONField(default="{}"),
        ),
    ]
