# Generated by Django 5.0 on 2024-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0009_consentrequest_additional_requests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequest",
            name="consent_request_sent_status",
            field=models.CharField(
                choices=[("SENT", "Sent"), ("CREATED", "Created")],
                default="CREATED",
                max_length=55,
            ),
        ),
    ]
