# Generated by Django 5.0 on 2024-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0010_consentrequest_consent_request_sent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequest",
            name="consent_request_form_title",
            field=models.CharField(default="Consent Request Form", max_length=455),
        ),
    ]
