# Generated by Django 5.0 on 2024-02-28 14:51

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0012_consentrequest_created_at_consentrequest_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consentrequest",
            name="created_by",
        ),
        migrations.AddField(
            model_name="consentrequest",
            name="created_by_user",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_request_form_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
