# Generated by Django 5.0 on 2024-02-28 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0013_remove_consentrequest_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consentrequest",
            old_name="created_by_user",
            new_name="created_by_user_id",
        ),
    ]
