# Generated by Django 5.0 on 2024-02-28 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "custom_accounts",
            "0014_rename_created_by_user_consentrequest_created_by_user_id",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consentrequest",
            name="created_by_user_id",
        ),
    ]
