# Generated by Django 5.0 on 2024-02-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0015_remove_consentrequest_created_by_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequest",
            name="consent_form_delete_status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("DELETED", "Deleted")],
                default="ACTIVE",
                max_length=55,
            ),
        ),
        migrations.AlterField(
            model_name="consentrequest",
            name="consent_requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consent_requested_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
