# Generated by Django 5.0 on 2024-02-28 16:19

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0016_consentrequest_consent_form_delete_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequest",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_request_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
