# Generated by Django 5.0 on 2024-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0017_consentrequest_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
