# Generated by Django 5.0 on 2024-02-28 16:33

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0018_consentrequest_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRequestFormSendToUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_request_form_sent_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_request_form_sent_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consent_requestform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_request",
                        to="custom_accounts.consentrequest",
                    ),
                ),
                (
                    "sent_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_request_form_sent_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
