# Generated by Django 5.0 on 2024-02-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0019_consentrequestformsendtouser"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequestformsendtouser",
            name="consent_answer_status",
            field=models.CharField(
                choices=[("REQUESTED", "Requested"), ("RESPONDED", "Responded")],
                default="REQUESTED",
                max_length=100,
            ),
        ),
    ]
