# Generated by Django 5.0 on 2024-02-29 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0020_consentrequestformsendtouser_consent_answer_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRequestFormResponseODRL",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("odrl_consent_additional_constraints", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consentrequestsendtouserformid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_request_sent_to_user_form",
                        to="custom_accounts.consentrequestformsendtouser",
                    ),
                ),
                (
                    "data_controller_processor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_requested_by_controller_processor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
