# Generated by Django 5.0 on 2024-02-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0021_consentrequestformresponseodrl"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequestformresponseodrl",
            name="consented_by_user",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consented_given_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
