# Generated by Django 5.0 on 2024-03-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0022_consentrequestformresponseodrl_consented_by_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrequestformresponseodrl",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="consentrequestformsendtouser",
            name="additional_constraints",
            field=models.JSONField(default={"permission_status": "Permission"}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consentrequestformsendtouser",
            name="consent_given_status",
            field=models.CharField(default="NotGiven", max_length=100),
        ),
        migrations.AlterField(
            model_name="consentrequestformsendtouser",
            name="consent_answer_status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("RESPONDED", "Responded"),
                    ("REVOKED", "Revoked"),
                ],
                default="REQUESTED",
                max_length=100,
            ),
        ),
    ]
