# Generated by Django 5.0 on 2024-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_accounts", "0023_consentrequestformresponseodrl_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentrequestformsendtouser",
            name="consent_given_status",
            field=models.CharField(default="Requested", max_length=100),
        ),
    ]
